name: Image snapshots

on:
  push:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - run: make snapshot
      - name: Archive snapshot artifacts
        uses: actions/upload-artifact@v4
        with:
          name: binaries
          path: dist/
